version: "3.8"

volumes:
  pgdata: 
  kongadata:
  rabbitmq_data:

services:
  #################################################
  # Customer: The Customer microservice
  #################################################
  customer:
    build:
      context: ./backend
      dockerfile: ./Customer/customer.Dockerfile
    # image: 
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      CUSTOMER_DB_URL: ${CUSTOMER_DB_URL}
    ports:
    - "5001:5001"
    # networks:
    #   - kong-net
  #################################################
  # Catalog: The Catalog microservice
  #################################################
  catalog:
    build:
      context: ./backend
      dockerfile: ./Catalog/catalog.Dockerfile
    # image: 
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      CATALOG_DB_URL: ${CATALOG_DB_URL}
    ports:
    - "5002:5002"
    expose:
    - "27017"
    # networks:
    #   - kong-net
  #################################################
  # Booking: The Booking microservice
  #################################################
  booking:
    build:
      context: ./backend
      dockerfile: ./Booking/booking.Dockerfile
    # image: 
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      BOOKING_DB_URL: ${BOOKING_DB_URL}
    ports:
    - "5003:5003"
    # networks:
    #   - kong-net
  #################################################
  # WaitList: The WaitList microservice
  #################################################
  waitlist:
    build:
      context: ./backend
      dockerfile: ./WaitList/waitlist.Dockerfile
    # image: 
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      WAITLIST_DB_URL: ${WAITLIST_DB_URL}
    ports:
    - "5010:5010"
    # networks:
    #   - kong-net
  #################################################
  # Payment: The Payment microservice
  #################################################
  payment:
    build:
      context: ./backend
      dockerfile: ./Payment/payment.Dockerfile
    # image: 
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      stripe_url: http://stripe-api:5016/api/stripepay
    ports:
      - "5004:5004"
    # networks:
    #   - kong-net
  #################################################
  # Notification: The Notification microservice
  #################################################
  notification:
    build:
      context: ./backend
      dockerfile: ./Notification/notification.Dockerfile
    # image: 
    restart: always
    depends_on:
      rabbitmq:
        condition: service_started
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      telegram_url: http://telegram-send-api:5015
      twilio_url: http://twilio-sendgrid-api:5014
    # networks:
    #   - kong-net

  ###################################
  # Error: The Error microservice
  ###################################
  error:
    build:
      context: ./backend
      dockerfile: ./Error/error.Dockerfile
    # image: 
    restart: always
    depends_on:
      rabbitmq:
        condition: service_started
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
    # networks:
    #   - kong-net

  ###################################################
  # Telegram Send API: The Telegram Send Message API
  ###################################################
  telegram-send-api:
    build:
      context: ./backend
      dockerfile: ./APIs/telegram_send_api.Dockerfile
    # image: 
    restart: always
    depends_on:
      notification:
        condition: service_started
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      PYTHONUNBUFFERED: 1
    ports:
      - "5015:5015"
    # networks:
    #   - kong-net

  ###################################################
  # Twilio Sendgrid API: The Twilio Email API
  ###################################################
  twilio-sendgrid-api:
    build:
      context: ./backend
      dockerfile: ./APIs/twilio_sendgrid_api.Dockerfile
    # image: 
    restart: always
    depends_on:
      notification:
        condition: service_started
    environment:
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      PYTHONUNBUFFERED: 1
    ports:
      - "5014:5014"
    # networks:
    #   - kong-net

  ###################################################
  # Stripe API: The Stripe Payment API
  ###################################################
  stripe-api:
    build:
      context: ./backend
      dockerfile: ./APIs/stripe_api.Dockerfile
    # image: 
    restart: always
    # depends_on:
      # payment:
      #   condition: service_healthy
    environment:
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      PYTHONUNBUFFERED: 1
    ports:
      - "5016:5016"
    # networks:
    #   - kong-net
  ####################################
  # RabbitMQ: The messaging broker
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    # networks:
    #   - kong-net