version: "3.8"

volumes:
  pgdata: 
  kongadata:
  rabbitmq_data:

services:
  #################################################
  # Customer: The Customer microservice
  #################################################
  customer:
    build:
      context: ./backend
      dockerfile: customer.Dockerfile
    # image: 
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      DB_URL: ${CUSTOMER_DB_URL}
    # networks:
    #   - kong-net
  #################################################
  # Catalog: The Catalog microservice
  #################################################
  catalog:
    build:
      context: ./backend
      dockerfile: catalog.Dockerfile
    # image: 
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      DB_URL: ${CATALOG_DB_URL}
    # networks:
    #   - kong-net
  #################################################
  # WaitList: The WaitList microservice
  #################################################
  waitlist:
    build:
      context: ./backend
      dockerfile: waitlist.Dockerfile
    # image: 
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      DB_URL: ${WAITLIST_DB_URL}
    # networks:
    #   - kong-net
  #################################################
  # Payment: The Payment microservice
  #################################################
  payment:
    build:
      context: ./backend
      dockerfile: payment.Dockerfile
    # image: 
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      stripe_url: http://stripe-api:5014
    # networks:
    #   - kong-net
  #################################################
  # Notification: The Notification microservice
  #################################################
  notification:
    build:
      context: ./backend
      dockerfile: notification.Dockerfile
    # image: 
    restart: always
    depends_on:
      rabbitmq:
        condition: service_started
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      telegram_url: http://telegram-send-api:5015
      twilio_url: http://twilio-sendgrid-api:5014
    # networks:
    #   - kong-net

  ###################################
  # Error: The Error microservice
  ###################################
  error:
    build:
      context: ./backend
      dockerfile: error.Dockerfile
    # image: 
    restart: always
    depends_on:
      rabbitmq:
        condition: service_started
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
    # networks:
    #   - kong-net

  ###################################################
  # Telegram Send API: The Telegram Send Message API
  ###################################################
  telegram-send-api:
    build:
      context: ./backend
      dockerfile: telegram_send_api.Dockerfile
    # image: 
    restart: always
    depends_on:
      notification:
        condition: service_started
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      PYTHONUNBUFFERED: 1
    # networks:
    #   - kong-net

  ###################################################
  # Twilio Sendgrid API: The Twilio Email API
  ###################################################
  twilio-sendgrid-api:
    build:
      context: ./backend
      dockerfile: twilio_sendgrid_api.Dockerfile
    # image: 
    restart: always
    depends_on:
      notification:
        condition: service_started
    environment:
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      PYTHONUNBUFFERED: 1
    # networks:
    #   - kong-net

  ###################################################
  # Stripe API: The Stripe Payment API
  ###################################################
  stripe-api:
    build:
      context: ./backend
      dockerfile: stripe_api.Dockerfile
    # image: 
    restart: always
    # depends_on:
      # payment:
      #   condition: service_healthy
    environment:
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      PYTHONUNBUFFERED: 1
    # networks:
    #   - kong-net
  ####################################
  # RabbitMQ: The messaging broker
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    # networks:
    #   - kong-net