apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -o kompose
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: catalog
  name: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: catalog
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -o kompose
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/greentable-kong-net: "true"
        io.kompose.service: catalog
    spec:
      containers:
        - env:
            - name: CATALOG_DB_URL
              value: ${CATALOG_DB_URL}
            - name: GOOGLE_API_KEY
              value: ${GOOGLE_API_KEY}
            - name: PYTHONUNBUFFERED
              value: "1"
          image: catalog
          name: catalog
          ports:
            - containerPort: 5002
          resources: {}
      restartPolicy: Always
status: {}
