apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file .\docker-compose-resolved.yml convert -o kompose
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.network/greentable-kong-net: "true"
    io.kompose.service: kong-migration
  name: kong-migration
spec:
  containers:
    - args:
        - kong
        - migrations
        - bootstrap
      env:
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_PG_HOST
          value: kong-database
        - name: KONG_PG_PASSWORD
          value: password
        - name: KONG_PG_USER
          value: kong
      image: kong:2.0.4
      name: kong-migration
      resources: {}
  restartPolicy: OnFailure
status: {}
